name: get-typing-data
on:
  schedule:
  - cron: "0 12 1 * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  get-and-commit:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract typing data.
        working-directory: ${{ github.workspace }}
        run: curl https://api.monkeytype.com/users/filipr1/profile -f -o "index.json"
      - uses: stefanzweifel/git-auto-commit-action@v5
