name: get-typing-data
on:
  schedule:
  - cron: "0 12 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  get-and-commit:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Extract typing data.
        run: curl https://api.monkeytype.com./users/filipr1/profile -o "typing.txt"
      - uses: freierson/monkeytype-widget@v5
